name: Build and Deploy Blog

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install Pandoc
        run: sudo apt-get install -y pandoc
      
      - name: Convert Markdown to HTML
        run: |
          mkdir -p posts
          if compgen -G "blog-posts/*.md" > /dev/null; then
            for file in blog-posts/*.md; do
              filename=$(basename "$file" .md)
              title=$(grep '^#title ' "$file" | sed 's/#title //')
              date=$(grep '^#date ' "$file" | sed 's/#date //')
              excerpt=$(awk 'NR>2 && NR<=7' "$file" | tr '\n' ' ')
              pandoc "$file" -f markdown -t html -o "posts/$filename.html"
            done
          else
            echo "<html><body><h1>No Blog Posts Found</h1></body></html>" > posts/index.html
          fi
      
      - name: Generate posts.json
        run: |
          echo "Generating posts.json..."
          echo '[' > posts.json
          first=true
          for file in blog-posts/*.md; do
            echo "Processing: $file"
            
            filename=$(basename "$file" .md)
            title=$(grep '^#title ' "$file" | sed 's/#title //')
            date=$(grep '^#date ' "$file" | sed 's/#date //')
            excerpt=$(awk 'NR>2 && NR<=7' "$file" | tr '\n' ' ')

            # Debugging: Print extracted values
            echo "Extracted title: $title"
            echo "Extracted date: $date"
            echo "Extracted excerpt: $excerpt"

            # Skip if title or date is missing
            if [ -z "$title" ] || [ -z "$date" ]; then
              echo "Skipping $file (Missing title or date)"
              continue
            fi

            if [ "$first" = true ]; then
              first=false
            else
              echo ',' >> posts.json
            fi
            echo "  {\"slug\": \"$filename\", \"title\": \"$title\", \"date\": \"$date\", \"excerpt\": \"$excerpt\"}" >> posts.json
          done
          echo ']' >> posts.json

          # Debugging: Print posts.json to confirm it exists
          echo "Final posts.json contents:"
          cat posts.json

      - name: Ensure posts.json is Added
        run: |
          if [ -f "posts.json" ]; then
            echo "posts.json exists. Adding it to git..."
          else
            echo "ERROR: posts.json was not found!"
            exit 1
          fi
      
      - name: Checkout repository with Token
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # Ensure posts.json exists and is not empty
          if [ -s "posts.json" ]; then
            echo "posts.json exists and is not empty. Adding it to git..."
          else
            echo "ERROR: posts.json is empty or missing!"
            exit 1
          fi

          # Debugging: Show file status before commit
          git status
          
          # Ensure Git recognizes changes
          git add posts.json posts || echo "Nothing to add"
          git commit -m "Auto-generate blog posts" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
