name: Build and Deploy Blog

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install Pandoc
        run: sudo apt-get install -y pandoc
      
      - name: Convert Markdown to HTML
        run: |
          mkdir -p posts
          for file in blog-posts/*.md; do
            filename=$(basename "$file" .md)
            pandoc "$file" -f markdown -t html -o "posts/$filename.html"
          done
      
      - name: Generate posts.json
        run: |
          echo '[' > posts.json
          first=true
          for file in blog-posts/*.md; do
            filename=$(basename "$file" .md)
            title=$(head -n 1 "$file" | sed 's/# //')
            date=$(git log -1 --format=%ci "$file")
            excerpt=$(head -n 5 "$file" | tail -n 3 | tr '\n' ' ')
            if [ "$first" = true ]; then
              first=false
            else
              echo ',' >> posts.json
            fi
            echo "  {\"slug\": \"$filename\", \"title\": \"$title\", \"date\": \"$date\", \"excerpt\": \"$excerpt\"}" >> posts.json
          done
          echo ']' >> posts.json

      - name: Debug GitHub Token
        run: |
          echo "GitHub Token Length: ${#GH_TOKEN}"

      
      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/unclegun/unclegun.github.io.git
          git add posts posts.json
          git commit -m "Auto-generate blog posts" || echo "No changes to commit"
          git push origin main
