name: Build and Deploy Blog

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with Token
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          sudo apt-get install -y pandoc
          sudo apt-get install -y python3 python3-pip

      # 🔹 Run Python script to generate JSON **BEFORE** converting Markdown to HTML
      - name: Run Python Script to Generate posts.json
        run: |
          python3 scripts/convert_blog_to_json.py

      - name: Ensure posts.json is Present
        run: |
          ls -lah
          if [ -f "posts.json" ]; then
            echo "posts.json is still here before commit."
          else
            echo "ERROR: posts.json disappeared before commit!"
            exit 1
          fi

      # 🔹 NEW: Commit and Push Updated posts.json
      - name: Commit and Push Updated posts.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add posts.json
          git commit -m "Auto-update posts.json [skip ci]" || echo "No changes to commit"
          git push origin main

      # 🔹 Convert Markdown to HTML AFTER JSON is generated
      - name: Convert Markdown to HTML
        run: |
          mkdir -p posts
          if compgen -G "blog-posts/*.md" > /dev/null; then
            for file in blog-posts/*.md; do
              filename=$(basename "$file" .md)
              title=$(grep '^#title ' "$file" | sed 's/#title //')
              date=$(grep '^#date ' "$file" | sed 's/#date //')

              # Remove metadata lines (first two lines)
              sed '1,2d' "$file" > "temp.md"

              # Convert Markdown to HTML with custom template
              pandoc "temp.md" -f markdown -t html \
                --template=blog-template.html \
                -V title="$title" -V date="$date" \
                -o "posts/$filename.html"

              rm temp.md
            done
          else
            echo "<html><body><h1>No Blog Posts Found</h1></body></html>" > posts/index.html
          fi
